#' Assign species to mz values
#'
#' @param peak_df     Data.frame, as generated by \code{generate_peakdf()}
#' @param speciesdf   Data.frame, containing columns:
#'                            "Substrate"  Character, the substrate from which the species was generated (used as grouping variable )
#'                            "Species"    Character, the name of the species 
#'                            "mz"         Numeric, m/z of species.
#'                    Column names can be changed but have to be specified in thid case by \code{subset.col, species.col, mz.col}
#' @param subsetcol   Character, name of column in \code{speciesdf} to subset data by (eg. "Substrate") 
#' @param tol         Numeric, tolerance for assignment 
#' @param speciescol  Character, name of column in \code{speciesdf} containing names of species
#' @param mzcol       Character, name of column in \code{speciesdf} containing m/z of species
#' @param append      Logical, if \code{TRUE} the result is appended as additional columns to the origninal data. 
#'                    Otherwise only the resulting assignments are returned.
#'
#' @return Data.frame with assigned peaks if append is TRUE
#' @export
assign_species <- function(peak_df, 
                           speciesdf, 
                           subsetcol = "Substrate",
                           tol = 5,  
                           speciescol = "Species", 
                           mzcol = "mz", 
                           append = TRUE) {
  
  speciesdf <- dplyr::as_tibble(speciesdf)
  peak_df <- dplyr::as_tibble(peak_df)
  subsets <- unique(dplyr::pull(peak_df,subsetcol))
  
  res_df <- c()
  for(sub in subsets) {
    fmzlist <- speciesdf[speciesdf[,subsetcol] == sub,]
    fpeak_df <- data.frame(peak_df[peak_df[,subsetcol] == sub,],
                                  species = NA,
                                  mz.theo = NA,
                                  mz.diff = NA,
                                  mz.diff.ppm = NA) %>% dplyr::as_tibble()
    
    for(i in 1:dim(fpeak_df[, mzcol])[1]) {                # i index in fpeak_df, c_idx index in fmzlist
      mz <- fpeak_df[[i, mzcol]]
      closest_idx <-  AlzTools::getClosest(dplyr::pull(fmzlist, mzcol), mz)
      closest_mz <- dplyr::pull(fmzlist, mzcol)[closest_idx]
      
      if(closest_mz > mz - tol & closest_mz < mz + tol) {
        for(c_idx in closest_idx) {
          fpeak_df[i, "species"] <- paste(pull(fmzlist, speciescol)[closest_idx], collapse = ", ")
          #fpeak_df[c_idx, "species.substrate"] <- fmzlist[i, subset.col]
          fpeak_df[i, "mz.theo"] <- fmzlist[c_idx, mzcol]
          fpeak_df[i, "mz.diff"] <- round(abs(fmzlist[c_idx,mzcol] - mz),1)
          fpeak_df[i, "mz.diff.ppm"] <- round(abs(fmzlist[c_idx,mzcol] - mz)/mz*10^6,1)
        }
      }
      
    }
    res_df <- rbind(res_df, fpeak_df)
    
  } 
  
  
  
  if(append) {
    return(res_df)
  } else {
    return(res_df[,c("species","mz.theo","mz.diff","mz.diff.ppm")])
  }
}
