#' Assign species to mz values
#'
#' @param peak_df     Data.frame, as generated by \code{generate_peakdf()}
#' @param speciesdf   Data.frame, containing columns:
#'                            "Substrate"  Character, the substrate from which the species was generated (used as grouping variable )
#'                            "Species"    Character, the name of the species 
#'                            "mz"         Numeric, m/z of species.
#'                    Column names can be changed but have to be specified in thid case by \code{subset.col, species.col, mz.col}
#' @param subsetcol   Character, name of column in \code{speciesdf} to subset data by (eg. "Substrate") 
#' @param highMz      Numeric, if provided a second tolerance (\code{highMzTol}) for \code{mz >= highMz} will be used.
#' @param tol         Numeric, tolerance for assignment either in Da or ppm.
#' @param highMzTol   Numeric, tolerance for assignment for \code{mz >= highMz} either in Da or ppm.
#' @param tolppm      Logical, use relative tolerance in ppm (\code{tol} is multiplied by 1e-6 internally).
#' @param speciescol  Character, name of column in \code{speciesdf} containing names of species
#' @param mzcol       Character, name of column in \code{speciesdf} containing m/z of species
#' @param append      Logical, if \code{TRUE} the result is appended as additional columns to the origninal data. 
#'                    Otherwise only the resulting assignments are returned.
#'
#' @return Data.frame with assigned peaks if append is TRUE
#' @export
assign_species <- function(peak_df, 
                           speciesdf, 
                           subsetcol = "Substrate",
                           highMz = NA,
                           tol = 5, 
                           highMzTol = NA,
                           tolppm = FALSE,
                           speciescol = "Species", 
                           mzcol = "mz", 
                           append = TRUE) {
  if(!is.na(highMz)) {
    if(is.na(highMzTol)) {
      stop("No highMzTol provided!\n")
    }
  }
  
  speciesdf <- dplyr::as_tibble(speciesdf)
  peak_df <- dplyr::as_tibble(peak_df)
  if(!is.na(subsetcol)) {
    subsets <- unique(dplyr::pull(peak_df,subsetcol))
  } else {
    subsets <- NA
  }
  
  res_df <- c()
  original_tol <- tol # store original tol in case tol gets overwritten with high tol
  for(sub in subsets) { 
    if(!is.na(subsetcol)) { 
      fmzlist <- speciesdf[speciesdf[,subsetcol] == sub,]
      fpeak_df <- tibble::tibble(peak_df[peak_df[,subsetcol] == sub,], # prepare peakdf with empty cols for species assigment 
                                 species =  NA_character_,
                                 mz.theo = NA_real_,
                                 mz.diff = NA_real_,
                                 mz.diff.ppm = NA_real_) 
    } else { # no subsetting
      fmzlist <- speciesdf
      fpeak_df <- tibble::tibble(peak_df,
                                 species = NA_character_,
                                 mz.theo = NA_real_,
                                 mz.diff = NA_real_,
                                 mz.diff.ppm = NA_real_) 
    }
    
    for(i in 1:dim(fpeak_df[, mzcol])[1]) {  
      tol <- original_tol # restore orginal tol at the start of each iteration
      mz <- fpeak_df[[i, mzcol]]
      closest_idx <-  AlzTools::getClosest(dplyr::pull(fmzlist, mzcol), mz)
      closest_mz <- dplyr::pull(fmzlist, mzcol)[closest_idx]
      
      if(!is.na(highMz)) {
        if(mz >= highMz) {
          tol <- highMzTol
          
        }
      }
      
      if(tolppm) {
        tol_ <- mz * tol * 1e-6
      } else {
        tol_ <- tol
      }
      
      if(closest_mz > mz - tol_ & closest_mz < mz + tol_) {
        for(c_idx in closest_idx) {
          fpeak_df[i, "species"] <- paste(pull(fmzlist, speciescol)[closest_idx], collapse = ", ")
          fpeak_df[i, "mz.theo"] <- fmzlist[c_idx, mzcol]
          fpeak_df[i, "mz.diff"] <- round((fmzlist[c_idx,mzcol] - mz),4)
          fpeak_df[i, "mz.diff.ppm"] <- round(abs(fmzlist[c_idx,mzcol] - mz)/mz*1e6,1)
        }
      }
      
    }
    res_df <- rbind(res_df, fpeak_df)
    
  } 
  
  
  
  if(append) {
    return(res_df)
  } else {
    return(res_df[,c("species","mz.theo","mz.diff","mz.diff.ppm")])
  }
}
