#' Convert MALDIquant Spectra or peaks to data.frame
#'
#' @param spec        MALDIquant::MassObject (spectra or peaks).
#' @param ID          Character, name (ID) of spectra.
#' @param plotIdx     Numeric, index in list of spectra.
#' 
#' @importFrom MALDIquant isMassPeaks isMassSpectrum isMassSpectrumOnDisk mass intensity
#'
#' @return
#'
.convertSpec <- function(spec, ID, plotIdx) {
  if(!length(ID)==1) {
    stop("Length of ID has to be one.\n")
  }
  if(isMassPeaks(spec)) {
    df <- tibble::tibble(ID = ID, 
                         plotIdx = plotIdx,
                         peakIdx = paste0(plotIdx, "_", 1:length(MALDIquant::mass(spec))),
                         mz = mass(spec), 
                         int = intensity(spec), 
                         SNR = snr(spec),
                         type = "peak")
  } else if (isMassSpectrum(spec) || isMassSpectrumOnDisk(spec)) {
    df <- tibble::tibble(ID = ID, 
                         plotIdx = plotIdx,
                         peakIdx = NA,
                         mz = mass(spec), 
                         int = intensity(spec),
                         type = "spectrum")
  } else if(is.list(spec)) {
    stop("spec was a list. Has to be a single (MALDIquant) object.\n")
  } else {
    stop("spec was no valid MALDIquant object.\n")
  }
  return(df)
}

#' Convert MALDIquant::MassSpectrum to tibble
#'
#' @param spec              (list of) MALDIquant::MassSpectrum 
#' @param peaks             (list of) MALDIquant::MassPeaks. Optinal. 
#' @param result_df         Data.frame, annotations as generated by \code{AssaySupport::generate_resultdf}.
#' @param nameFromMetaData  Logical, get names from metaData or from named list.
#' @param unlist            Logical, unlist result.
#' 
#' @importFrom dplyr bind_rows
#'
#' @return
#' tibble with spectra and peak data.
#' @export
spec2df <- function(spec, peaks, result_df, nameFromMetaData = FALSE, unlist = TRUE) {
  if(!missing(peaks)) {
    if(MALDIquant:::.isMassObjectList(spec)) {
      if(!length(spec) == length(peaks)) {
        stop("Length of spec and peaks does not match!\n")
      }
    } 
  } else {
    if(!missing(result_df)) {
      stop("Annoation data can only be used in combination with peaks.\n")
    }
  }
  
  
  noNames <- FALSE
  if(nameFromMetaData) {
    if(is.list(spec)) {
      names <- vapply(spec, function(x) {
        md <- metaData(x)
        nm <- md[[grep("name", names(md))]]
        return(nm)
      }, "a")
    } else {
      md <- metaData(spec)
      names <- md[[grep("name", names(md))]]
    }
    
    if(any(is.na(names))) {
      noNames <- TRUE
    }
  } else if(!is.null(names(spec))) {
    names <- names(spec)
  } else {
    noNames <- TRUE
  }
  
  if(noNames) {
    warning("spectra were not named, no IDs assigned!\n")
    if(is.list(spec)) {
      names <- rep(NA, length(spec))
    } else {
      names <- NA
    }
  }
  if(is.list(spec)) {
    df_spec <- lapply(1:length(spec), function(i) {
      return(AssaySupport:::.convertSpec(spec[[i]], names[[i]], i))
    })
  } else {
    df_spec <- AssaySupport:::.convertSpec(spec, names[1], 1)
  }
  
  if(!missing(peaks)) {
    if(is.list(peaks)) {
      df_peaks <- lapply(1:length(spec), function(i) {
        return(AssaySupport:::.convertSpec(peaks[[i]], names[[i]], i))
      })
      
    } else {
      df_peaks <- AssaySupport:::.convertSpec(peaks, names[1], 1)
    }
    df <- bind_rows(df_spec, df_peaks)
    if(!missing(result_df)) {
      df <- left_join(df, result_df %>%
                        ungroup() %>%
                        select(peakIdx, species), 
                      by = "peakIdx")
    }
  } else {
    df <- df_spec
  }
  if(!unlist) {
    return(df)
  }
  return(bind_rows(df))
}

#' ggplot wrapper to plot spectra
#'
#' @param df        tibble, as generated by spec2df()
#' @param aes       ggplot aesthetic mapping. See \code{ggplot2::aes}.
#' @param minSNR    numeric, filter peaks with snr lower then minSNR.
#' @param scale     numeric or character, either numeric to multiply intensity or "min" or "max" to scale spectra to specified measure.
#' @param round     integer, number of digits to display in plot.
#' @param peakLabel character, type a label assigned to peaks. For "name" and "mz_name" a annotation is needed. See \code{AssaySupport::spec2df}.
#'
#' @importFrom ggplot2 aes ggplot geom_line geom_point theme
#' @importFrom ggrepel geom_text_repel
#' @importFrom dplyr summarise
#' 
#' @return
#' ggplot object.
#' @export
ggSpectrum <- function(df, 
                       aes = aes_string(x = "mz", y = "int", col = "ID"),
                       minSNR = 1, 
                       scale = 100, 
                       round = 1, 
                       peakLabel = c("none", "mz", "name", "mz_name")) {
  peakLabel <- match.arg(peakLabel)
  if(is.numeric(scale)) {
    df$int <- df$int * 100
  } else switch (scale,
                 max = df <- df %>%
                   group_by(ID) %>%
                   mutate(int = int/max(int)),
                 min = df <- df %>%
                   group_by(ID) %>%
                   mutate(int = int/min(int))
  )
  
  if("SNR" %in% colnames(df)) {
    
    df <- df %>%
      mutate(mzlabel = ifelse(!is.na(SNR), round(mz, round), NA))
    
    peakdf <- df %>%
      filter(!is.na(mzlabel)) %>%
      filter(SNR > minSNR) 
    
    
    
    if(peakLabel %in% c("name", "mz_name")) {
      if(!"species" %in% colnames(df)) {
        stop("No annotation data supplied. Can't name peaks.\n")
      }
      switch(peakLabel, name = {
        anno <- df %>%
          filter(!is.na(mzlabel)) %>%
          filter(SNR > minSNR,
                 !is.na(species)) %>%
          group_by(mz, species) %>%
          arrange(desc(int)) %>%
          summarise(int = first(int),
                    label = first(species),
                    ID = first(ID))
      },
      mz_name = {
        anno <- df %>%
          filter(!is.na(mzlabel)) %>%
          filter(SNR > minSNR,
                 !is.na(species)) %>%
          group_by(mz, species) %>%
          arrange(desc(int)) %>%
          summarise(int = first(int),
                    label = paste0(first(mzlabel), " - ", first(species)),
                    ID = first(ID))
      }) 
      
      
      
      
    }
  }
    
    
    
    
      p <- ggplot(df, aes) 
    
    
    p <- p +
      geom_line() +
      theme(legend.position = "bottom")
    
    if("SNR" %in% colnames(df)) {
      p <- p +
        geom_point(data = peakdf, aes(x = mz, y = int), alpha = 0.75) 
      
      if(peakLabel == "mz")  {
        p <- p +
          ggrepel::geom_text_repel(data = peakdf, aes(x = mz, y = int, label = label),
                                   segment.colour = "grey", 
                                   min.segment.length = 0, 
                                   col = "black")
      }
      if(peakLabel %in% c("name", "mz_name")) {
        p <- p +
          ggrepel::geom_text_repel(data = anno, aes(x = mz, y = int, label = label),
                                   segment.colour = "grey", 
                                   min.segment.length = 0, 
                                   col = "black")
      }
      
      
    }
    return(p)
  }
  
  
  