#' Product profile plot
#' 
#' Generates a product profile plot.
#' Uses a stacked bar plot on percentage values normalized to total product intensity 
#' to visulize shifts in the profile.
#'
#' @param resultdf Data.frame as generated by \code{generate_resultdf}
#' @param group_var Character, colname in resultdf used for grouping (x-axis of the resulting plot).
#' @param select_species Character, the name of the target analyte. 
#' This is used in a grepl so it can also be a fragment of the full name (e.g. Ab for Abx_y).
#' @param filter Character, names to filter out.
#' This is used in a grepl so it can also be a fragment of the full name (e.g. IS for IS_Ab1_28).
#' @param show_legend Logical, show legend in addition to labels.
#'
#' @return
#' ggplot object
#' @importFrom dplyr filter group_by mutate 
#' @importFrom ggplot2 ggplot aes theme geom_col geom_text position_stack labs element_text 
#' @importFrom ggpubr theme_pubr 

profilePlot <- function(resultdf, group_var, select_species = "Ab", filter = "IS", show_legend = FALSE) {
  if(missing(group_var)) {
    stop("group_var not supplied.\n")
  }
  
  p <- resultdf %>%
    filter(grepl(pattern = select_species, x = species),
           !grepl(pattern = filter, x = species)) %>%
    group_by({{ group_var }}) %>%
    mutate(total = sum(int)) %>%
    mutate(norm = int/total*100) %>% # recalculate total product intensity after filtering
    ggplot(aes(x = {{ group_var }}, y = norm, fill = species)) +
    geom_col(position = "stack") +
    geom_text(aes(label = vapply(species,
                                 function(x) unlist(strsplit(x, "_"))[2],
                                 FUN.VALUE = "a")),
              position = position_stack(vjust = .5)) +
    theme_pubr() +
    labs(y = "%-total A\u03B2",
         x = "") +
    theme(axis.title = element_text(size = 18, face = "bold"),
          axis.text.x = element_text(size = 18, face = "bold"),
          strip.text = element_text(size = 18, face = "bold"))
  
  if(!show_legend) {
    return(p + theme(legend.position = "none"))
  } else {
    return(p)
  }
}
